# Workshop 1: Basics of Python and NumPy (2018)

#### Importing Libraries
By convention we import numpy as np

In [1]:
import numpy as np

## Creation
`ndarray` (n dimentional array) -> The basic datatype of numpy<br>
To create a 1d array we can pass a list of integers or floats or Boolean or any sort of object<br>
To create a 2d array we pass a list of lists

In [2]:
myarray = np.array([3,5,2,21])

In [3]:
print(myarray)

[ 3  5  2 21]


myarray

In [4]:
my2darray = np.array([ [5,6] , [3,4] ])
my2darray

array([[5, 6],
       [3, 4]])

More than one way of creating arrays<br>
`ones` -> creates an array of ones<br>
`zeros` -> creates an array of zeros

In [5]:
myzeros=np.zeros(3)
myzeros 

array([0., 0., 0.])

In [6]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Very important : <br>
`linspace` (a, b, n)-> creates an evenly spaced AP of n numbers between a and b (inclusive)

In [7]:
np.linspace(0, 10, 5 )

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

For non inclusive we use

In [8]:
np.linspace(0, 10, 5 ,endpoint=False)

array([0., 2., 4., 6., 8.])

Random arrays

In [9]:
a = np.array([1,2,3])
b = np.random.randint(0,10, (3,3))
print(a)
print(b)

[1 2 3]
[[8 3 7]
 [4 8 1]
 [7 6 0]]


## Shape Size and More
array.shape gives you the shape of the array (Surprising !¡)

In [10]:
myarray.shape

(4,)

In [11]:
my2darray.shape

(2, 2)

Now we can change the shape of the array after its creation. This doesnt change the original array

In [12]:
mynewarray = myarray.reshape(2,2)
mynewarray

array([[ 3,  5],
       [ 2, 21]])

It wont work if the sizes dont match

In [13]:
myarray.reshape(2,3)

ValueError: cannot reshape array of size 4 into shape (2,3)

There is also `size` and `ndim`

In [14]:
print(myarray.size,myarray.ndim)

4 1


## Indexing
We start from 0

In [15]:
print(myarray)

[ 3  5  2 21]


In [16]:
print(myarray[0],myarray[3])

3 21


We can go backwards as well with negative indexing

In [17]:
myarray[-1]

21

For 2d arrays we use double bracket notation <br>
`[row,column]`

In [18]:
my2darray

array([[5, 6],
       [3, 4]])

In [19]:
print(my2darray[0,0],my2darray[1,0])

5 3


In [20]:
my2darray[1]

array([3, 4])

## Slicing
`[start:stop:step]`

In [21]:
print(myarray)
print(myarray[1:3])

[ 3  5  2 21]
[5 2]


Can omit zero

In [22]:
print(myarray[:3])

[3 5 2]


In [23]:
myarray[::-1]

array([21,  2,  5,  3])

## Masking

In [24]:
mybigarray=np.random.randint(1,10,(9))
mybigarray

array([9, 3, 4, 4, 7, 9, 8, 6, 2])

In [25]:
mybigarray[mybigarray>5]

array([9, 7, 9, 8, 6])

In [26]:
true_false_array= (mybigarray>5)
true_false_array

array([ True, False, False, False,  True,  True,  True,  True, False])

In [27]:
mybigarray[true_false_array]

array([9, 7, 9, 8, 6])

(Greater than 2 and less than 7) or equal to 1

In [28]:
mybigarray[((mybigarray>2) & (mybigarray<7) )|(mybigarray==1)]

array([3, 4, 4, 6])

## Functions
press tab after . for suggestions

In [29]:
myarray

array([ 3,  5,  2, 21])

In [30]:
myarray.mean()

7.75

In [31]:
myarray.sort()
myarray  

array([ 2,  3,  5, 21])

In [33]:
np.sort(mybigarray)

array([2, 3, 4, 4, 6, 7, 8, 9, 9])

# Arithmetic

In [37]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print()
print(b)

[[3 9 7]
 [7 1 8]
 [5 2 5]]

[[1 5 8]
 [8 2 9]
 [1 9 4]]


In [38]:
a+3

array([[ 6, 12, 10],
       [10,  4, 11],
       [ 8,  5,  8]])

In [39]:
a+b

array([[ 4, 14, 15],
       [15,  3, 17],
       [ 6, 11,  9]])

Elementwise Multiplication

In [40]:
a*b

array([[ 3, 45, 56],
       [56,  2, 72],
       [ 5, 18, 20]])

Matrix Multiplication

In [41]:
a@b

array([[ 82,  96, 133],
       [ 23, 109,  97],
       [ 26,  74,  78]])